[pytest]
testpaths = tests

markers =
    api: API tests
    ui: UI tests
    smoke: smoke tests
    regression: regression tests

# Đã gộp các thông số cấu hình lại thành 1 dòng duy nhất
addopts = -v --tb=short --alluredir=reports/allure-results --clean-alluredir